const heroesDatabase = [
    { id: "lifestealer", slug: "life_stealer", name: "Lifestealer", role: "carry", winrate: "54.8%", 
      description: "Силовой лобовой керри, славящийся врожденным БКБ (Rage) и возможностью пожирать плотных танков за счет процентного отжора. Предпочитает затяжные драки один на один.",
      items: { starter: ["Radiance", "Armlet of Mordiggian", "Desolator"], core: ["Manta Style", "Skull Basher", "Assault Cuirass"], situational: ["Nullifier", "Silver Edge", "Abyssal Blade"] },
      counters: ["Necrophos", "Ursa", "Riki", "Pugna"], synergies: ["Io", "Tusk", "Oracle"], tips: "Фармите Radiance -> давите пространство. Используйте Rage для невосприимчивости к эффектам." },
    { id: "wk", slug: "skeleton_king", name: "Wraith King", role: "carry", winrate: "54.3%", 
      description: "Надежный и живучий кор-герой. Обладает критическими ударами, вампиризмом на команду и ультимейтом, дающим вторую жизнь, что делает его крайне сложной целью для быстрой инициации врага.",
      items: { starter: ["Radiance", "Armlet of Mordiggian", "Desolator"], core: ["Manta Style", "Skull Basher", "Assault Cuirass"], situational: ["Nullifier", "Silver Edge"] },
      counters: ["Anti-Mage", "Phantom Lancer", "Naga Siren"], synergies: ["Io", "Magnus", "Crystal Maiden"], tips: "Максимально быстро получайте реинкарнацию. Прожимайте Armlet прямо перед смертью." },
    { id: "nightstalker", slug: "night_stalker", name: "Night Stalker", role: "offlane", winrate: "55.3%", 
      description: "Гроза ночной карты. С наступлением темноты превращается в сверхагрессивного инициатора с огромной скоростью передвижения, плотностью и длительным безмолвием для вражеских кастеров.",
      items: { starter: ["Phase Boots", "Blink Dagger", "Black King Bar"], core: ["Assault Cuirass", "Skull Basher", "Aghanim's Shard"], situational: ["Nullifier", "Heart of Tarrasque"] },
      counters: ["Phoenix", "Naga Siren", "Spectre"], synergies: ["Io", "Spirit Breaker"], tips: "Максимально доминируйте в ночное время, используйте BKB для контроля карты." },
    { id: "doom", slug: "doom_bringer", name: "Doom", role: "offlane", winrate: "53.2%", 
      description: "Жадный хардлейнер с мощной экономикой за счет поедания крипов. Его ультимейт полностью выключает одного ключевого героя противника из командной драки, запрещая использовать способности и предметы.",
      items: { starter: ["Phase Boots", "Blink Dagger", "Shiva's Guard"], core: ["Refresher Orb", "Assault Cuirass", "Lotus Orb"], situational: ["Scythe of Vyse", "Heart of Tarrasque"] },
      counters: ["Oracle", "Abaddon", "Phantom Lancer"], synergies: ["Skywrath Mage", "Lion"], tips: "Поедайте нейтральных крипов со стабильным контролем или аурами. Ультимейт отдавайте в ключевой кор-таргет." },
    { id: "leshrac", slug: "leshrac", name: "Leshrac", role: "mid", winrate: "52.9%", 
      description: "Магический кор-герой, наносящий колоссальный непрерывный урон по области вокруг себя. Отлично уничтожает строения и требует предметов на выживаемость и манареген для поддержания ультимейта.",
      items: { starter: ["Bloodstone", "Shiva's Guard", "Black King Bar"], core: ["Eul's Scepter of Divinity", "Kaya and Sange", "Wind Waker"], situational: ["Scythe of Vyse", "Refresher Orb"] },
      counters: ["Anti-Mage", "Nyx Assassin", "Pugna"], synergies: ["Underlord", "Dark Seer"], tips: "Реализуйте быстрый сплит-пуш строений через Diabolic Edict." },
    { id: "clinkz", slug: "clinkz", name: "Clinkz", role: "carry", winrate: "53.7%", 
      description: "Скрытный убийца дальнего боя. Полагается на невидимость, внезапное нападение с огромной скоростью атаки и призыв скелетов-лучников. Способен за секунды аннигилировать одиночные цели.",
      items: { starter: ["Falcon Blade", "Desolator", "Orchid Malevolence"], core: ["Daedalus", "Black King Bar", "Hurricane Pike"], situational: ["Nullifier", "Scythe of Vyse"] },
      counters: ["Phantom Lancer", "Axe", "Legion Commander"], synergies: ["Vengeful Spirit", "Beastmaster"], tips: "Инициируйте ганги сразу после покупки Desolator. Грамотно занимайте позицию через Skeleton Walk." },
    { id: "sf", slug: "nevermore", name: "Shadow Fiend", role: "carry", winrate: "52.4%", 
      description: "Сноуболл-герой с колоссальным физическим и магическим потенциалом. Наращивает урон с каждой убитой душой и способен перевернуть драку одним точным прокастом Requiem of Souls из невидимости или Blink-инициации.",
      items: { starter: ["Power Treads", "Falcon Blade", "Mask of Madness"], core: ["Manta Style", "Daedalus", "Black King Bar"], situational: ["Butterfly", "Satanic"] },
      counters: ["Phantom Lancer", "Terrorblade", "Huskar"], synergies: ["Magnus", "Earthshaker"], tips: "Ускоряйте фарм. Использование Manta Style эффективно сбрасывает безмолвие (сайленс)." },
    { id: "ember", slug: "ember_spirit", name: "Ember Spirit", role: "mid", winrate: "51.8%", 
      description: "Невероятно мобильный и неуловимый мидер. Постоянно маневрирует по полю боя с помощью огненных ремнантов, нанося быстрый распределенный урон и связывая врагов цепями.",
      items: { starter: ["Maelstrom", "Black King Bar", "Aghanim's Shard"], core: ["Daedalus", "Blink Dagger", "Linken's Sphere"], situational: ["Refresher Orb", "Octarine Core"] },
      counters: ["Huskar", "Tinker", "Anti-Mage"], synergies: ["Earth Spirit", "Dark Willow"], tips: "Прокачивайте Searing Chains. Действуйте агрессивно, перемещаясь на ремнанты." },
    { id: "legion", slug: "legion_commander", name: "Legion Commander", role: "offlane", winrate: "52.1%", 
      description: "Инициатор, заставляющий противника вступить в честный поединок один на один (Duel). С каждой выигранной дуэлью необратимо увеличивает свой урон, превращаясь к лейт-гейму в смертоносную угрозу.",
      items: { starter: ["Blink Dagger", "Blade Mail", "Black King Bar"], core: ["Assault Cuirass", "Desolator", "Aghanim's Scepter"], situational: ["Silver Edge", "Nullifier"] },
      counters: ["Oracle", "Tusk", "Shadow Demon", "Winter Wyvern"], synergies: ["Skywrath Mage", "Lina"], tips: "Инициируйте Duel строго при огневой поддержке ваших союзников." },
    { id: "spiritbreaker", slug: "spirit_breaker", name: "Spirit Breaker", role: "support", winrate: "53.0%", 
      description: "Глобальный заводила драки. Способен выбрать целью любого врага на карте и устремиться к нему сквозь любые препятствия, оглушая всех на своем пути и координируя внезапные ганги команды.",
      items: { starter: ["Phase Boots", "Shadow Blade", "Black King Bar"], core: ["Assault Cuirass", "Aghanim's Scepter", "Lotus Orb"], situational: ["Silver Edge", "Heaven's Halberd"] },
      counters: ["Eul's Scepter of Divinity", "Winter Wyvern", "Shadow Demon"], synergies: ["Zeus", "Nature's Prophet"], tips: "Постоянно перемещайтесь по карте (чардж), создавая хаос и отпушивая лайны." },
    { id: "puck", slug: "puck", name: "Puck", role: "mid", winrate: "52.0%", 
      description: "Один из самых ловких и неуловимых магов в игре. Обладает множеством механик уклонения от урона и сильным контролем по области (Dream Coil), способным сорвать позиционку всей вражеской команде.",
      items: { starter: ["Witch Blade", "Blink Dagger", "Eul's Scepter of Divinity"], core: ["Linken's Sphere", "Shiva's Guard", "Octarine Core"], situational: ["Refresher Orb", "Scythe of Vyse"] },
      counters: ["Ember Spirit", "Huskar", "Anti-Mage"], synergies: ["Dark Willow", "Void Spirit"], tips: "Используйте Phase Shift для уклонения от ключевых направленных заклинаний." },
    { id: "nagasiren", slug: "naga_siren", name: "Naga Siren", role: "carry", winrate: "51.7%", 
      description: "Иллюзионист-макрогигант. За счет армии копий выкачивает золото со всей карты, лишая врага ресурсов. В драках зачищает цели через снижение брони, а ультимейтом (Song) идеально начинает или завершает сражения.",
      items: { starter: ["Manta Style", "Diffusal Blade", "Heart of Tarrasque"], core: ["Butterfly", "Eye of Skadi", "Skull Basher"], situational: ["Nullifier", "Bloodthorn"] },
      counters: ["Earthshaker", "Leshrac", "Sven"], synergies: ["Io", "Luna"], tips: "Контролируйте карту и экономику врага параллельным распределением иллюзий." },
    { id: "phantomlancer", slug: "phantom_lancer", name: "Phantom Lancer", role: "carry", winrate: "51.9%", 
      description: "Керри, создающий бесконечную лавину иллюзий прямо во время атаки. Буквально за секунды выжигает ману целям и сеет хаос, заставляя врагов тратить ключевые АоЕ-способности впустую.",
      items: { starter: ["Diffusal Blade", "Manta Style", "Aghanim's Shard"], core: ["Heart of Tarrasque", "Butterfly", "Skull Basher"], situational: ["Nullifier", "Eye of Skadi"] },
      counters: ["Earthshaker", "Legion Commander", "Axe"], synergies: ["Magnus", "Dark Seer"], tips: "Затягивайте драки, размножая иллюзии. Diffusal Blade быстро выжигает ману целям." },
    { id: "axe", slug: "axe", name: "Axe", role: "offlane", winrate: "52.6%", 
      description: "Агрессивный танк, жаждущий оказаться в самом центре вражеской группы. Агрит врагов способностью Berserker's Call, заставляя их атаковать себя и умирать от разрушительных пассивных контратак Counter Helix.",
      items: { starter: ["Blink Dagger", "Blade Mail", "Vanguard"], core: ["Shiva's Guard", "Heart of Tarrasque", "Aghanim's Scepter"], situational: ["Lotus Orb", "Crimson Guard"] },
      counters: ["Necrophos", "Oracle", "Dazzle"], synergies: ["Lich", "Skywrath Mage"], tips: "Комбинация Berserker's Call + Blade Mail моментально уничтожает плотных физических коров." },
    { id: "oracle", slug: "oracle", name: "Oracle", role: "support", winrate: "51.4%", 
      description: "Командный спаситель с высоким порогом вхождения. Манипулирует механиками лечения, очищения и защиты от магии. Его ультимейт откладывает весь получаемый союзником урон, удваивая входящий хил.",
      items: { starter: ["Arcane Boots", "Glimmer Cape", "Force Staff"], core: ["Aeon Disk", "Holy Locket", "Eul's Scepter of Divinity"], situational: ["Ghost Scepter", "Aghanim's Scepter"] },
      counters: ["Silencer", "Anti-Mage", "Nyx Assassin"], synergies: ["Huskar", "Legion Commander"], tips: "False Promise — ультимативный сейв союзников от фокуса, Дуэли или ультимейтов." },
    { id: "hoodwink", slug: "hoodwink", name: "Hoodwink", role: "support", winrate: "50.8%", 
      description: "Подвижный и каверзный саппорт-снайпер. Контролирует врагов, привязывая их к деревьям (Bushwhack), рикошетит желудями и наносит сокрушительный урон с огромной дистанции с помощью ультимейта.",
      items: { starter: ["Urn of Shadows", "Eul's Scepter of Divinity", "Gleipnir"], core: ["Aghanim's Shard", "Blink Dagger", "Scythe of Vyse"], situational: ["Meteor Hammer"] },
      counters: ["Storm Spirit", "Puck"], synergies: ["Techies", "Clockwerk"], tips: "Контролируйте врагов из тумана войны, кастуйте Sharpshooter через деревья." },
    { id: "zeus", slug: "zuus", name: "Zeus", role: "mid", winrate: "51.2%", 
      description: "Чистокровный магический прокастер. Обрушивает на головы врагов тонны молний, подсвечивает невидимок и карту, а его визитная карточка (Thundergod's Wrath) бьет по всем героям противника, где бы они ни находились.",
      items: { starter: ["Aether Lens", "Kaya", "Octarine Core"], core: ["Refresher Orb", "Eul's Scepter of Divinity", "Aghanim's Scepter"], situational: ["Ghost Scepter", "Linken's Sphere"] },
      counters: ["Anti-Mage", "Spectre", "Phantom Lancer"], synergies: ["Spirit Breaker", "Nature's Prophet"], tips: "Вносите global урон по карте. Держите позиционку глубоко в тылу." },
    { id: "undying", slug: "undying", name: "Undying", role: "support", winrate: "52.3%", 
      description: "Доминатор ранней стадии игры и линий. Медленно высасывает силу у врагов, делая их хрупкими, а в замесах устанавливает сокрушительную надгробие (Tombstone), бесконечно порождающую замедятющих зомби.",
      items: { starter: ["Arcane Boots", "Holy Locket", "Solar Crest"], core: ["Crimson Guard", "Pipe of Insight", "Aeon Disk"], situational: ["Shiva's Guard"] },
      counters: ["Ursa", "Lifestealer"], synergies: ["Venomancer", "Warlock"], tips: "Ставьте Tombstone в недосягаемости для быстрой атаки. Скампливайте Decay." }
];